# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mastodon-blender-view.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mastodon-blender-view.proto',
  package='mastodon_blender_view',
  syntax='proto3',
  serialized_options=b'\n\014org.mastodonB\017HelloWorldProtoP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1bmastodon-blender-view.proto\x12\x15mastodon_blender_view\"K\n\x14\x41\x64\x64MovingSpotRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x63oordinates\x18\x02 \x03(\x02\x12\x12\n\ntimepoints\x18\x03 \x03(\x05\"\x07\n\x05\x45mpty2k\n\x0bViewService\x12\\\n\raddMovingSpot\x12+.mastodon_blender_view.AddMovingSpotRequest\x1a\x1c.mastodon_blender_view.Empty\"\x00\x42\'\n\x0corg.mastodonB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_ADDMOVINGSPOTREQUEST = _descriptor.Descriptor(
  name='AddMovingSpotRequest',
  full_name='mastodon_blender_view.AddMovingSpotRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='mastodon_blender_view.AddMovingSpotRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='coordinates', full_name='mastodon_blender_view.AddMovingSpotRequest.coordinates', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timepoints', full_name='mastodon_blender_view.AddMovingSpotRequest.timepoints', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=129,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='mastodon_blender_view.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=138,
)

DESCRIPTOR.message_types_by_name['AddMovingSpotRequest'] = _ADDMOVINGSPOTREQUEST
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddMovingSpotRequest = _reflection.GeneratedProtocolMessageType('AddMovingSpotRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDMOVINGSPOTREQUEST,
  '__module__' : 'mastodon_blender_view_pb2'
  # @@protoc_insertion_point(class_scope:mastodon_blender_view.AddMovingSpotRequest)
  })
_sym_db.RegisterMessage(AddMovingSpotRequest)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'mastodon_blender_view_pb2'
  # @@protoc_insertion_point(class_scope:mastodon_blender_view.Empty)
  })
_sym_db.RegisterMessage(Empty)


DESCRIPTOR._options = None

_VIEWSERVICE = _descriptor.ServiceDescriptor(
  name='ViewService',
  full_name='mastodon_blender_view.ViewService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=140,
  serialized_end=247,
  methods=[
  _descriptor.MethodDescriptor(
    name='addMovingSpot',
    full_name='mastodon_blender_view.ViewService.addMovingSpot',
    index=0,
    containing_service=None,
    input_type=_ADDMOVINGSPOTREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VIEWSERVICE)

DESCRIPTOR.services_by_name['ViewService'] = _VIEWSERVICE

# @@protoc_insertion_point(module_scope)
