# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mastodon-blender-view.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mastodon-blender-view.proto',
  package='mastodon_blender_view',
  syntax='proto3',
  serialized_options=b'\n\014org.mastodonB\017HelloWorldProtoP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1bmastodon-blender-view.proto\x12\x15mastodon_blender_view\"\x07\n\x05\x45mpty\"Z\n\x14\x41\x64\x64MovingSpotRequest\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05label\x18\x02 \x01(\t\x12\x13\n\x0b\x63oordinates\x18\x03 \x03(\x02\x12\x12\n\ntimepoints\x18\x04 \x03(\x05\"3\n\x14SetSpotColorsRequest\x12\x0b\n\x03ids\x18\x01 \x03(\r\x12\x0e\n\x06\x63olors\x18\x02 \x03(\r\"(\n\x13SetTimePointRequest\x12\x11\n\ttimepoint\x18\x01 \x01(\r\" \n\x12\x41\x63tiveSpotResponse\x12\n\n\x02id\x18\x01 \x01(\r\"\"\n\x14SetActiveSpotRequest\x12\n\n\x02id\x18\x01 \x01(\r2\xef\x03\n\x0bViewService\x12\\\n\raddMovingSpot\x12+.mastodon_blender_view.AddMovingSpotRequest\x1a\x1c.mastodon_blender_view.Empty\"\x00\x12\\\n\rsetSpotColors\x12+.mastodon_blender_view.SetSpotColorsRequest\x1a\x1c.mastodon_blender_view.Empty\"\x00\x12Z\n\x0csetTimePoint\x12*.mastodon_blender_view.SetTimePointRequest\x1a\x1c.mastodon_blender_view.Empty\"\x00\x12j\n\x1bsubscribeToActiveSpotChange\x12\x1c.mastodon_blender_view.Empty\x1a).mastodon_blender_view.ActiveSpotResponse\"\x00\x30\x01\x12\\\n\rsetActiveSpot\x12+.mastodon_blender_view.SetActiveSpotRequest\x1a\x1c.mastodon_blender_view.Empty\"\x00\x42\'\n\x0corg.mastodonB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='mastodon_blender_view.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=61,
)


_ADDMOVINGSPOTREQUEST = _descriptor.Descriptor(
  name='AddMovingSpotRequest',
  full_name='mastodon_blender_view.AddMovingSpotRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='mastodon_blender_view.AddMovingSpotRequest.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='label', full_name='mastodon_blender_view.AddMovingSpotRequest.label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='coordinates', full_name='mastodon_blender_view.AddMovingSpotRequest.coordinates', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timepoints', full_name='mastodon_blender_view.AddMovingSpotRequest.timepoints', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=153,
)


_SETSPOTCOLORSREQUEST = _descriptor.Descriptor(
  name='SetSpotColorsRequest',
  full_name='mastodon_blender_view.SetSpotColorsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='mastodon_blender_view.SetSpotColorsRequest.ids', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='colors', full_name='mastodon_blender_view.SetSpotColorsRequest.colors', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=206,
)


_SETTIMEPOINTREQUEST = _descriptor.Descriptor(
  name='SetTimePointRequest',
  full_name='mastodon_blender_view.SetTimePointRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timepoint', full_name='mastodon_blender_view.SetTimePointRequest.timepoint', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=248,
)


_ACTIVESPOTRESPONSE = _descriptor.Descriptor(
  name='ActiveSpotResponse',
  full_name='mastodon_blender_view.ActiveSpotResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='mastodon_blender_view.ActiveSpotResponse.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=282,
)


_SETACTIVESPOTREQUEST = _descriptor.Descriptor(
  name='SetActiveSpotRequest',
  full_name='mastodon_blender_view.SetActiveSpotRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='mastodon_blender_view.SetActiveSpotRequest.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=318,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['AddMovingSpotRequest'] = _ADDMOVINGSPOTREQUEST
DESCRIPTOR.message_types_by_name['SetSpotColorsRequest'] = _SETSPOTCOLORSREQUEST
DESCRIPTOR.message_types_by_name['SetTimePointRequest'] = _SETTIMEPOINTREQUEST
DESCRIPTOR.message_types_by_name['ActiveSpotResponse'] = _ACTIVESPOTRESPONSE
DESCRIPTOR.message_types_by_name['SetActiveSpotRequest'] = _SETACTIVESPOTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'mastodon_blender_view_pb2'
  # @@protoc_insertion_point(class_scope:mastodon_blender_view.Empty)
  })
_sym_db.RegisterMessage(Empty)

AddMovingSpotRequest = _reflection.GeneratedProtocolMessageType('AddMovingSpotRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDMOVINGSPOTREQUEST,
  '__module__' : 'mastodon_blender_view_pb2'
  # @@protoc_insertion_point(class_scope:mastodon_blender_view.AddMovingSpotRequest)
  })
_sym_db.RegisterMessage(AddMovingSpotRequest)

SetSpotColorsRequest = _reflection.GeneratedProtocolMessageType('SetSpotColorsRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETSPOTCOLORSREQUEST,
  '__module__' : 'mastodon_blender_view_pb2'
  # @@protoc_insertion_point(class_scope:mastodon_blender_view.SetSpotColorsRequest)
  })
_sym_db.RegisterMessage(SetSpotColorsRequest)

SetTimePointRequest = _reflection.GeneratedProtocolMessageType('SetTimePointRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETTIMEPOINTREQUEST,
  '__module__' : 'mastodon_blender_view_pb2'
  # @@protoc_insertion_point(class_scope:mastodon_blender_view.SetTimePointRequest)
  })
_sym_db.RegisterMessage(SetTimePointRequest)

ActiveSpotResponse = _reflection.GeneratedProtocolMessageType('ActiveSpotResponse', (_message.Message,), {
  'DESCRIPTOR' : _ACTIVESPOTRESPONSE,
  '__module__' : 'mastodon_blender_view_pb2'
  # @@protoc_insertion_point(class_scope:mastodon_blender_view.ActiveSpotResponse)
  })
_sym_db.RegisterMessage(ActiveSpotResponse)

SetActiveSpotRequest = _reflection.GeneratedProtocolMessageType('SetActiveSpotRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETACTIVESPOTREQUEST,
  '__module__' : 'mastodon_blender_view_pb2'
  # @@protoc_insertion_point(class_scope:mastodon_blender_view.SetActiveSpotRequest)
  })
_sym_db.RegisterMessage(SetActiveSpotRequest)


DESCRIPTOR._options = None

_VIEWSERVICE = _descriptor.ServiceDescriptor(
  name='ViewService',
  full_name='mastodon_blender_view.ViewService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=321,
  serialized_end=816,
  methods=[
  _descriptor.MethodDescriptor(
    name='addMovingSpot',
    full_name='mastodon_blender_view.ViewService.addMovingSpot',
    index=0,
    containing_service=None,
    input_type=_ADDMOVINGSPOTREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='setSpotColors',
    full_name='mastodon_blender_view.ViewService.setSpotColors',
    index=1,
    containing_service=None,
    input_type=_SETSPOTCOLORSREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='setTimePoint',
    full_name='mastodon_blender_view.ViewService.setTimePoint',
    index=2,
    containing_service=None,
    input_type=_SETTIMEPOINTREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='subscribeToActiveSpotChange',
    full_name='mastodon_blender_view.ViewService.subscribeToActiveSpotChange',
    index=3,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_ACTIVESPOTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='setActiveSpot',
    full_name='mastodon_blender_view.ViewService.setActiveSpot',
    index=4,
    containing_service=None,
    input_type=_SETACTIVESPOTREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VIEWSERVICE)

DESCRIPTOR.services_by_name['ViewService'] = _VIEWSERVICE

# @@protoc_insertion_point(module_scope)
